# Generated by Django 6.0.1 on 2026-01-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
